[package]
name = "lunir-luau"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lunir = "0.2.0"
num_enum = "0.5.11"
